"""Eskom integrated reports: electricity generated by open-cycle gas turbines.

The turbines burn diesel, so their output is the verified basis for diesel
used in power generation. Each integrated report gives, for Eskom's
financial year (1 April to 31 March, named by the year it ends):

  - output of Eskom's own turbines, for the report year and the two before
    it (the generation table: "Open-cycle gas turbines (OCGTs) a b c");
  - combined output of Eskom's and the independent producers' turbines, for
    the report year and the one before ("x GWh Eskom and IPP OCGTs (y: z GWh)").

Independent-producer output is the difference between the two.

These are GWh of electricity, not litres of diesel. Turning them into
litres needs a turbine efficiency and an energy content for diesel; that
conversion is a model assumption and is deliberately not done here.
"""
from __future__ import annotations

import hashlib
import re
import urllib.request
from dataclasses import dataclass
from pathlib import Path

INDEX_URL = "https://www.eskom.co.za/investors/integrated-results/"
USER_AGENT = "Mozilla/5.0 (lfm source fetcher)"

SERIES = ("eskom_ocgt", "eskom_and_ipp_ocgt")

_REPORT_LINK = re.compile(
    r'href="([^"]*integrated-report[^"]*?((?:19|20)\d{2})\.pdf)"', re.IGNORECASE,
)
# A GWh figure as printed: "811" or "2 176".
_GWH = r"((?:\d{1,2} )?\d{3})"
_YEARS = re.compile(r"GWh (20\d{2}) (20\d{2}) (20\d{2})")
_OWN = re.compile(r"Open-cycle gas turbines \(OCGTs\) " + " ".join([_GWH] * 3))
_COMBINED = re.compile(
    _GWH + r" ?GWh Eskom and IPP OCGTs \((20\d{2}): " + _GWH + r" ?GWh\)"
)


@dataclass(frozen=True)
class Report:
    year: int
    url: str
    path: Path | None = None
    sha256: str | None = None


def discover_reports(index_html: str) -> list[Report]:
    """Integrated reports linked from the results page, oldest first."""
    found = {int(year): href for href, year in _REPORT_LINK.findall(index_html)}
    return [Report(year=y, url=found[y]) for y in sorted(found)]


def fetch_index(url: str = INDEX_URL) -> str:
    return _get(url).decode("utf-8", errors="replace")


def download(report: Report, raw_dir: Path) -> Report:
    raw_dir.mkdir(parents=True, exist_ok=True)
    path = raw_dir / f"eskom-integrated-report-{report.year}.pdf"
    if not path.exists():
        data = _get(report.url)
        if not data.startswith(b"%PDF"):
            raise ValueError(f"{report.url} did not return a PDF")
        path.write_bytes(data)
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return Report(year=report.year, url=report.url, path=path, sha256=digest)


def _get(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=300) as response:
        return response.read()


def pdf_text(path: Path) -> list[str]:
    """Page text with whitespace collapsed (needs ``pypdf`` and ``cryptography``)."""
    try:
        from pypdf import PdfReader
    except ImportError as exc:  # pragma: no cover - environment dependent
        raise ImportError(
            'Reading the reports needs pypdf. Install with: pip install -e ".[data]"'
        ) from exc

    import logging

    logging.getLogger("pypdf").setLevel(logging.ERROR)
    pages = []
    for page in PdfReader(str(path)).pages:
        try:
            pages.append(re.sub(r"\s+", " ", page.extract_text() or ""))
        except Exception:  # noqa: BLE001 - one unreadable page must not stop the rest
            pages.append("")
    return pages


def parse_report(pages: list[str]) -> tuple[dict[int, list], list[str]]:
    """Turbine output from one report: ``({financial year: [own, combined]}, warnings)``.

    A figure the report does not give is ``None``.
    """
    rows: dict[int, list] = {}
    warnings: list[str] = []

    own_found = False
    for text in pages:
        years = _YEARS.search(text)
        own = _OWN.search(text)
        if years and own:
            for year, value in zip(years.groups(), own.groups()):
                rows.setdefault(int(year), [None, None])[0] = _gwh(value)
            own_found = True
            break
    if not own_found:
        warnings.append("Eskom turbine output table not found")

    combined_found = False
    for text in pages:
        match = _COMBINED.search(text)
        if not match:
            continue
        this_value, prior_year, prior_value = match.groups()
        prior = int(prior_year)
        rows.setdefault(prior + 1, [None, None])[1] = _gwh(this_value)
        rows.setdefault(prior, [None, None])[1] = _gwh(prior_value)
        combined_found = True
        break
    if not combined_found:
        warnings.append("combined Eskom and IPP turbine output not found")

    return rows, warnings


def _gwh(text: str) -> float:
    return float(text.replace(" ", ""))
